# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-27 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200127_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_slug',
        ),
    ]
