# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200128_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
