# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-29 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_sale',
            name='category',
        ),
        migrations.DeleteModel(
            name='Product_sale',
        ),
    ]
